.TH PACKDDIR "1" "June 2003"  "User Commands"
.SH NAME
upackddir \- extract PackdDir files.
.SH SYNOPSIS
.B upackddir
[
.I options
]
\fBFILENAME...\fR
.SH DESCRIPTION
.PP
Extracts and create PackdDir files.

By default \fBupackddir\fR extracts the given file, if \fBFILENAME\fR is '-'
stdin will be used.
.SH OPTIONS
.TP
\fB\-t, \-\-list\fR
just list the contents of the archive.
.TP
\fB\-c, \-\-create\fR
create a new archive.
.TP
\fB\-f, \-\-file=ARG\fR
use this filename for a newly created archive. Default is stdout.
.TP
\fB\-x FILE\fR
extracts FILE from the packddir archive, can be used multiple times.
.TP
\fB\-\-help\fR
display help and exit.
.TP
\fB\-\-version\fR
output version information and exit.
.SH EXAMPLES
Extracting a PackdDir file:
.br
	upackddir foo.pak

Creating a PackdDir file:
.br
	upackddir -c . > currentdirectory.pak
.br
	upackddir -cf currentdirectory.pak .
.br
	upackddir -cf variuous.pak /root /var /tmp
.SH AUTHOR
Written by Fabio Bonelli.
.SH "REPORTING BUGS"
Report bugs to <fabiobonelli@libero.it>.
.SH COPYRIGHT
Copyright \(co 2003 Fabio Bonelli.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
